#!/bin/bash

distrobox-export-electron code
distrobox-export-electron obsidian
distrobox-export -a onlyoffice-desktopeditors -ef '--xdg-desktop-portal' -nf '--additional-flags "--env GTK_IM_MODULE=xim"'
